### PR TITLE
RedisStorage retrieve optimization

### PR DESCRIPTION
**Pull request by red-led**
If value is not stored redis `get` will return false, so there's no need to send 2 requests.

### CODE REVIEW

**Comment by red-led** [comment]
@olvlvl can you review this?

**Comment by olvlvl** [comment]
With this change, if I store `false` I'll get `null` retrieving it.

**Comment by red-led** [comment]
@olvlvl, Redis can store only string values, so `Redis::get` will return either string (something stored) or false (nothing found).

`RedisStorage::store` call [serializes](https://github.com/ICanBoogie/Storage/blob/master/lib/RedisStorage.php#L80) all values, so for Redis `false` looks like string `b:0;`.

`RedisStorage::retrieve` will [unserialize](https://github.com/ICanBoogie/Storage/pull/11/commits/ac7cb8629cc512cbc06b1d64eeffb14c029fd126#diff-be980adb38d4b4fbec9437e26ef14235L50-L52) it back to `false`.

**Comment by red-led** [comment]
@olvlvl, I added a bunch of test's to ensure you it's ok. 
But `FileStorage` fails it, because it follows different logic and [eliminates key](https://github.com/ICanBoogie/Storage/blob/master/lib/FileStorage.php#L122) if `false` is passed.
Is it intended behavior or bug?

**Comment by olvlvl** [comment]
@red-led I try to merge but tests failed: https://travis-ci.org/github/ICanBoogie/Storage/builds/681843673 I restored master.

**Comment by red-led** [comment]
I was hoping for further discussion about tests and fixing them before merge. See #12.

**Comment by olvlvl** [comment]
@red-led Do you mind rebasing your branch against master and opening a new PR?

**Comment by red-led** [comment]
Done: https://github.com/ICanBoogie/Storage/pull/13

**Pull request merged**
